service: set-syncer # NOTE: update this with your service name

app: set-syncer-dev
tenant: modahqi

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  profile: default
  environment:
    SpotifyClientId:     ${file(./config.json):SPOTIFY_CLIENT_ID}
    SpotifyClientSecret: ${file(./config.json):SPOTIFY_CLIENT_SECRET}
    YoutubeApiKey:       ${file(./config.json):YOUTUBE_API_KEY}
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - s3:PutObject
        - s3:ListBucket
      Resource: "arn:aws:s3:::first-set"
  resources:
    - ${file(resources/s3.yml)}  

plugins:
  - serverless-plugin-include-dependencies
  - serverless-offline

functions:
  differ:
    handler: src/Differ.main
    events:
      - http:
          path: ''
          method: get

  downloader:
    handler: src/Downloader.main
