Resources:
  FirstSetBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - DELETE
            MaxAge: 3000

# Print out the name of the bucket that is created
Outputs:
  FirstSetBucket:
    Value:
      Ref: FirstSetBucket